packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.130'
  - '@tailwindcss/node@4.3.1'
  - '@tailwindcss/oxide-android-arm64@4.3.1'
  - '@tailwindcss/oxide-darwin-arm64@4.3.1'
  - '@tailwindcss/oxide-darwin-x64@4.3.1'
  - '@tailwindcss/oxide-freebsd-x64@4.3.1'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.1'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.1'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.1'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.1'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.1'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.1'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.1'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.1'
  - '@tailwindcss/oxide@4.3.1'
  - '@tailwindcss/vite@4.3.1'
  - ai@6.0.204
  - deslop-js@0.0.24
  - eslint@10.5.0
  - ink@7.0.6
  - oxlint-plugin-react-doctor@0.5.2
  - react-doctor@0.5.2
  - tailwindcss@4.3.1
