it.skipIf(!process.env.DATABASE_URL)("gated test", () => {}); // HIT
test.runIf(ok)("gated test", () => {}); // HIT
it.concurrent.skipIf(!ok)("concurrent gated test", () => {}); // HIT
test.sequential.runIf(ok)("sequential gated test", () => {}); // HIT
it("options skip", { skip: !process.env.DATABASE_URL }, () => {}); // HIT
test("options todo", { todo: !ok }, () => {}); // HIT
it("shorthand skip", { skip }, () => {}); // HIT
it("options by &&", ok && { skip: true }, () => {}); // HIT
it[mode]("computed modifier", () => {}); // HIT
it("getter", { get skip() { return !url; } }, () => {}); // HIT
it("quoted key", { "skip": !url }, () => {}); // HIT
it("asserted options", ({ skip: !url }) as TestOptions, () => {}); // HIT
it("satisfies options", { todo: !ok } satisfies TestOptions, () => {}); // HIT
it.each([1, 2])("each with options %s", { skip: !ok }, () => {}); // HIT
