it("runs", () => {});
test.concurrent("concurrent test", () => {});
it.each([1, 2])("table %s", () => {});
expect(/skipIf/.test(source)).toBe(true);
submit.skipIf("an unrelated member");
it("a plain skipped test through options", { skip: true }, () => {});
it("a todo through options", { todo: true }, () => {});
it("other options", { timeout: 5_000, retry: 2 }, () => {});
it.each([{ skip: maybe }])("table rows are data, not options %o", () => {});
const dbTest = test.extend({ ...baseFixtures, todo: async ({}, use) => use([]) });
it("skip: false", { skip: false }, () => {});
test.scoped({ skip: maybe });
it("a computed literal key", { ["skip"]: true }, run);
it("a timeout picked between numbers", () => {}, process.env.CI ? 60_000 : 5_000);
it(process.env.NAME ?? "a name picked at run time", () => {});
it("a timeout computed from a pick", async () => {}, Number(process.env.SLOW_TIMEOUT ?? 60_000));
it.each(rows.filter((row) => row.enabled ?? true))("a pick inside a filter callback %o", () => {});
var sameTest = test.extend({});
var sameTest = test.extend({});
sameTest("declarations that agree", () => {});
it("a test expected to fail", { fails: true }, () => {});
it("a body read out of a fixed array", [() => {}][0]);
it("an options object nested in a body's closure", () => {
  const options = { skip: !process.env.DATABASE_URL };
  expect(options).toBeDefined();
});
it("a string pick after the name", () => {}, process.env.CI ? "a" : "b");
it("a fails key under meta", { meta: { fails: process.env.CI === "true" } }, () => {});
it("a timeout parsed from the environment", () => {}, parseInt(process.env.SLOW_TIMEOUT ?? "5000", 10));
it("a timeout bounded by Math.max", () => {}, Math.max(Number(process.env.SLOW_TIMEOUT ?? 0), 5_000));
it("a body built by a helper naming no skip", withLogging("cache warm-up", async () => {}));
it("a body built by a helper with a picked option value", withOptions({ timeout: process.env.CI ? 10_000 : 5_000 }, async () => {}));
it("a body built by a helper whose string mentions todo: nothing", withLogging("todo: tracked in #12", async () => {}));
