import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const DEFAULT_CONFIG_PATH = "askdb.config.ts";

/**
 * Single template: only `askdb.config.ts` is written. Guidance that used to live in a generated
 * `.env` file lives in comments here. Use `env("NAME")` for any variable from a local `.env`
 * (when loaded via `import "dotenv/config"`) or from the process environment.
 */
const CONFIG_TEMPLATE = `import "dotenv/config";
import { defineConfig, env, type AskDbConfig } from "@askdb/config";

/**
 * Nested AskDB configuration (grouped like Prisma's \`defineConfig\`).
 *
 * \`import "dotenv/config"\` loads a local \`.env\` when this file is evaluated (missing file is OK).
 * First-party CLIs call \`bootstrapAskDbEnv\`, which loads \`.env\` then evaluates this file and installs the AskDB runtime snapshot.
 *
 * Use \`env("VAR")\` for values read from the environment (shell or \`.env\`). Missing values are OK at
 * file load time; \`flattenAskDbConfig\` applies documented defaults for optional fields.
 *
 * \`satisfies AskDbConfig\` validates the nested shape at compile time.
 *
 * ---------------------------------------------------------------------------
 * Optional \`.env\` (not generated by \`askdb init\`) — example keys you can set:
 * ---------------------------------------------------------------------------
 *
 *   # Local secrets (do not commit \`.env\`).
 *
 *   # --- AI (OpenAI-compatible) ---
 *   # Required for live NL→SQL unless you use ASKDB_MOCK_SQL in tests.
 *   MY_OPENAI_API_KEY=
 *   # MY_OPENAI_BASE_URL=
 *
 *   # Chat model id — optional; defaults are applied when unset (see \`@askdb/config\` / flattenAskDbConfig).
 *   MY_CHAT_MODEL=gpt-4o-mini
 *
 *   # --- Postgres (live DB URL for introspection + connectors) ---
 *   MY_DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
 *   #
 *   # Pagila dev fixture (docker compose -f fixtures/pagila/docker-compose.yml up --build -d → port 5433):
 *   # MY_DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5433/pagila
 *
 *   # Default Schema v2 output for \`askdb introspect\` when you omit --out (maps to ASKDB_INTROSPECT_OUT)
 *   MY_INTROSPECT_OUTPUT_DIR=./askdb/
 *
 *   # Optional: different URL for introspection only — add in this file, e.g.
 *   #   introspection.providerConfig.postgres.databaseUrl: env("MY_INTROSPECT_DATABASE_URL")
 *   # MY_INTROSPECT_DATABASE_URL=
 *
 *   # --- Prisma schema-file introspection (optional) ---
 *   # When using \`askdb introspect --engine prisma\`, add a prisma branch below and e.g. env("MY_PRISMA_SCHEMA").
 *   # MY_PRISMA_SCHEMA=./prisma
 *
 *   # --- RAG (optional; defaults below are mock embedder + in-memory store) ---
 *   # MY_RAG_EMBEDDER=mock
 *   # MY_PGVECTOR_URL=postgres://postgres:postgres@127.0.0.1:5434/askdb_rag
 *
 *   # --- Logging / modes (optional) ---
 *   # MY_ASKDB_LOG_LEVEL=info
 *   # MY_ASKDB_CORRELATION_ID=
 *   # MY_ASKDB_MODE=schema_only   # schema_only | bounded_results
 *   # MY_ASKDB_OMIT_SENSITIVE_FROM_PROMPT=true
 *
 *   # --- Host defaults (optional) ---
 *   # MY_ASKDB_SCHEMA_PATH=fixtures/schemas/orders-users.schema
 *
 * You can rename keys freely — update the \`env("...")\` calls to match.
 *
 * For Postgres introspection, omit \`introspection.providerConfig.postgres.databaseUrl\` to reuse
 * \`database.providerConfig.postgres.databaseUrl\` as \`DATABASE_URL\`.
 */
export default defineConfig({
  ai: {
    // openai | azure | foundry (foundry maps to Azure-compatible env vars)
    provider: "openai",
    providerConfig: {
      openai: {
        // Optional until live NL→SQL; then use env("MY_OPENAI_API_KEY") or your own key name.
        apiKey: "",
        model: env("MY_CHAT_MODEL"),
      },
    },
  },

  database: {
    // postgres (more dialects later)
    provider: "postgres",
    providerConfig: {
      postgres: {
        databaseUrl: env("MY_DATABASE_URL"),
      },
    },
  },

  introspection: {
    // postgres | prisma
    provider: "postgres",
    providerConfig: {
      postgres: {
        // Omit databaseUrl to reuse database.providerConfig.postgres.databaseUrl (see flattenAskDbConfig).
      },
    },
    outputDir: env("MY_INTROSPECT_OUTPUT_DIR"),
  },

  rag: {
    // mock | openai | ai-sdk
    embedder: "mock",
    embedderConfig: {},
    // file | memory | pgvector
    store: "memory",
    storeConfig: {
      memory: {},
    },
  },
} satisfies AskDbConfig);
`;

type InitOptions = {
  force: boolean;
  path: string;
};

export function runInitCli(argv: readonly string[]): number {
  let opts: InitOptions;
  try {
    opts = parseOptions(argv);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    process.stderr.write(`${msg}\n`);
    return 1;
  }

  if (opts.path === "--help" || opts.path === "-h") {
    printHelp();
    return 0;
  }

  const configTarget = resolve(process.cwd(), opts.path);

  if (existsSync(configTarget) && !opts.force) {
    process.stderr.write(
      `Refusing to overwrite existing file:\n` +
        `  - ${configTarget}\n` +
        `Use \`askdb init --force\` to overwrite.\n`,
    );
    return 1;
  }

  try {
    writeFileSync(configTarget, CONFIG_TEMPLATE, { encoding: "utf8" });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    process.stderr.write(`Failed to write init template: ${msg}\n`);
    return 1;
  }

  process.stdout.write(
    `Wrote:\n` +
      `  - ${configTarget}\n` +
      "Next steps:\n" +
      "  1. Create a `.env` (optional) or export variables to match the `env(\"...\")` calls in this file — see the header comment for examples.\n" +
      "  2. For live NL→SQL, set an OpenAI-compatible key (or use ASKDB_MOCK_SQL in tests).\n" +
      "  3. For a Schema v2 directory from Postgres/Prisma: `askdb introspect ...` (see --help). With MY_INTROSPECT_OUTPUT_DIR / ASKDB_INTROSPECT_OUT you can omit `--out` when a default output dir is set.\n" +
      "  4. With an existing schema artifact: `askdb ask --schema <path> --question \"...\"`.\n",
  );
  return 0;
}

function parseOptions(argv: readonly string[]): InitOptions {
  const opts: InitOptions = { force: false, path: DEFAULT_CONFIG_PATH };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    switch (arg) {
      case "--force":
      case "-f":
        opts.force = true;
        break;
      case "--path": {
        const value = argv[++i];
        if (!value || value.startsWith("--")) {
          throw new Error(`${arg} requires a value.`);
        }
        opts.path = value;
        break;
      }
      case "--help":
      case "-h":
        opts.path = "--help";
        return opts;
      default:
        throw new Error(`Unknown option: ${arg}`);
    }
  }
  return opts;
}

function printHelp(): void {
  process.stdout.write(
    [
      "askdb init - Create askdb.config.ts (nested defineConfig template with env() examples and .env guidance in comments)",
      "",
      "Usage:",
      "  askdb init                    Create ./askdb.config.ts (refuses to overwrite unless --force)",
      "  askdb init --force            Overwrite an existing askdb.config.ts",
      "  askdb init --path <file>      Write the template to a custom file path",
      "",
    ].join("\n"),
  );
}
